#配置端口
server:
  port: 8400
  servlet:
    context-path: /check_service_manage

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8

  redis:
    #Redis数据库索引（默认为0）
    database: 12
    #Redis连接地址
    host: www.king2.cn
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）//
    password: liuzijiang1314
    #连接超时时间（毫秒）
    timeout: 1000

